
services:
  eureka-server:
    build: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - quiz-network

  question-service:
    build: ./question-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      POSTGRES_USER: surro
      POSTGRES_PASSWORD: secret
      POSTGRES_URL: jdbc:postgresql://question-db:5432/question-service-db
    ports:
      - "8080:8080"
    networks:
      - quiz-network
    depends_on:
      - question-db
      - eureka-server
  question-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: surro
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: question-service-db
    ports:
      - "5433:5432"
    networks:
      - quiz-network
    volumes:
      - postgres-question-data:/var/lib/postgresql

  quiz-service:
    build: ./quiz-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      POSTGRES_USER: surro
      POSTGRES_PASSWORD: secret
      POSTGRES_URL: jdbc:postgresql://quiz-db:5432/quiz-service-db
    ports:
      - "8090:8080"
    networks:
      - quiz-network
    depends_on:
      - question-db
      - eureka-server
  quiz-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: surro
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: quiz-service-db
    ports:
      - "5434:5432"
    networks:
      - quiz-network
    volumes:
      - postgres-quiz-data:/var/lib/postgresql
  api-gateway:
    build: ./api-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      KEYCLOAK_PROVIDER_URI: http://keycloak:8080/realms/quiz-app
      KEYCLOAK_CLIENT_ID: oauth-client
      KEYCLOAK_CLIENT_SECRET: secret
    ports:
      - "8765:8080"
    networks:
      - quiz-network
    depends_on:
      - eureka-server
      - keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    ports:
      - "9090:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge
volumes:
  postgres-question-data:
  postgres-quiz-data: