spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_PROVIDER_URI:http://localhost:9090/realms/quiz-app}
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:oauth-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:secret}
server:
  port: 8765